version: '3.0'

services:
  clickhouse:
    image: bitnami/clickhouse:latest
    volumes:
      - clickhouse-volume:/bitnami/clickhouse
      - ./config/clickhouse/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - '8123:8123'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

  pulsar:
    image: apachepulsar/pulsar-all:latest
    ports:
      - '8080:8080'
      - '6650:6650'
    command: bin/pulsar standalone
    environment:
      clusterName: 'cluster-a'
      managedLedgerDefaultEnsembleSize: '1'
      managedLedgerDefaultWriteQuorum: '1'
      managedLedgerDefaultAckQuorum: '1'
    volumes:
      - ./config/pulsar/setup.sh:/setup.sh


volumes:
  clickhouse-volume: {}
