version: '3.0'

services:
  clickhouse:
    image: bitnami/clickhouse:latest
    volumes:
      - clickhouse-volume:/bitnami/clickhouse
      - ./config/clickhouse/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - '8123:8123'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

  pulsar:
    image: apachepulsar/pulsar-all:latest
    ports:
      - '8080:8080'
      - '6650:6650'
    command: '/start-pulsar.sh'
    environment:
      clusterName: 'cluster-a'
      managedLedgerDefaultEnsembleSize: '1'
      managedLedgerDefaultWriteQuorum: '1'
      managedLedgerDefaultAckQuorum: '1'
#      advertisedAddress: 'pulsar'
    volumes:
      - ./start-pulsar.sh:/start-pulsar.sh
      - ./connector.yaml:/configs/clickhouse-connector.yaml
      - ./run-connector.sh:/run-connector.sh

volumes:
  clickhouse-volume: {}
