# Для внутренних запросов
apiVersion: v1
kind: Service
metadata:
  name: hadoop-historyserver-svc
  labels:
    app: hadoop-historyserver
spec:
  selector:
    app: hadoop-historyserver
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-historyserver
  labels:
    app: hadoop-historyserver
spec:
  selector:
    matchLabels:
      app: hadoop-historyserver
  serviceName: hadoop-historyserver-svc
  replicas: 1
  template:
    metadata:
      name: hadoop-historyserver
      labels:
        app: hadoop-historyserver
    spec:
      containers:
        - name: historyserver
          image: bde2020/hadoop-historyserver:2.0.0-hadoop3.1.3-java8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50070
            - containerPort: 9870
            - containerPort: 9000
          env:
            - name: 'CLUSTER_NAME'
              value: 'dhwms'
          envFrom:
            - configMapRef:
                name: hadoop-config
          volumeMounts:
            - mountPath: /hadoop/dfs/name
              name: namenode-volume
            - name: files-volume
              mountPath: /etc/files
      volumes:
        - name: files-volume
          hostPath:
            path: /home/ash-blade/Downloads/anime
  volumeClaimTemplates:
    - metadata:
        name: namenode-volume
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: '512Mi'
---
# Для запросов извне - веб-морда для HTTP
apiVersion: v1
kind: Service
metadata:
  name: hadoop-historyserver-gateway-svc
  labels:
    app: hadoop-historyserver-gateway-svc
spec:
  selector:
    app: hadoop-historyserver
  type: NodePort
  ports:
    - port: 9870
      targetPort: 9870
      protocol: TCP
      name: http