version: '3.0'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.3-java8
    ports:
      - '9870:9870'
    env_file:
      - ./hadoop.env
    environment:
      CLUSTER_NAME: 'dhwms'
    volumes:
      - namenode-volume:/hadoop/dfs/name
  datanode-0:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    ports:
      - '9864:9864'
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: 'namenode:9870'
    volumes:
      - datanode-0-volume:/hadoop/dfs/data
#  datanode-1:
#    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
#    ports:
#      - '9865:9864'
#    env_file:
#      - ./hadoop.env
#    environment:
#      SERVICE_PRECONDITION: 'namenode:9870'
#    volumes:
#      - datanode-1-volume:/hadoop/dfs/data
#  datanode-2:
#    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
#    ports:
#      - '9866:9864'
#    env_file:
#      - ./hadoop.env
#    environment:
#      SERVICE_PRECONDITION: 'namenode:9870'
#    volumes:
#      - datanode-2-volume:/hadoop/dfs/data

volumes:
  namenode-volume:
  datanode-0-volume:
#  datanode-1-volume:
#  datanode-2-volume: