version: '3.0'

services:
  pulsar-metadata-setup:
    image: apachepulsar/pulsar-all:latest
    entrypoint:
      - 'bash'
      - '-c'
      - 'bin/pulsar initialize-cluster-metadata \
         --cluster cluster-a \
         --zookeeper zookeeper:2181 \
         --configuration-store zookeeper:2181 \
         --web-service-url http://broker:8080 \
         --broker-service-url pulsar://broker:6650'
    depends_on:
      - zookeeper

  bookie:
    image: apachepulsar/pulsar-all:latest
    environment:
      zkServers: 'zookeeper:2181'
      metadataServiceUri: 'metadata-store:zk:zookeeper:2181'
    user: root
    command: bash -c "bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie"

    volumes:
    - bookie-volume:/pulsar/data/bookkeeper

  pulsar-base: &pulsar-base
    image: apachepulsar/pulsar-all:latest
    environment:
      zookeeperServers: 'zookeeper:2181'
      metadataStoreUrl: 'zk:zookeeper:2181'
      clusterName: 'cluster-a'
      managedLedgerDefaultEnsembleSize: '1'
      managedLedgerDefaultWriteQuorum: '1'
      managedLedgerDefaultAckQuorum: '1'
    command: bash -c "bin/apply-config-from-env.py conf/broker.conf && exec bin/pulsar broker"

  pulsar-0:
    <<: *pulsar-base
    ports:
      - '8080:8080'
      - '6650:6650'
    environment:
      zookeeperServers: 'zookeeper:2181'
      metadataStoreUrl: 'zk:zookeeper:2181'
      clusterName: 'cluster-a'
      managedLedgerDefaultEnsembleSize: '1'
      managedLedgerDefaultWriteQuorum: '1'
      managedLedgerDefaultAckQuorum: '1'
      advertisedAddress: 'localhost'

  pulsar-1:
    <<: *pulsar-base
    ports:
      - '8081:8080'
      - '6651:6650'
    environment:
      advertisedAddress: 'pulsar-1'

  pulsar-2:
    <<: *pulsar-base
    ports:
      - '8082:8080'
      - '6652:6650'

  zookeeper:
    image: apachepulsar/pulsar-all:latest
    environment:
      metadataStoreUrl: 'zk:zookeeper:2181'
      cluster-name: 'cluster-a'
      managedLedgerDefaultEnsembleSize: '1'
      managedLedgerDefaultWriteQuorum: '1'
      managedLedgerDefaultAckQuorum: '1'
    ports:
      - '2181:2181'
    user: root
    command:
      - 'bash'
      - '-c'
      - 'bin/apply-config-from-env.py conf/zookeeper.conf && bin/generate-zookeeper-config.sh conf/zookeeper.conf && exec bin/pulsar zookeeper'
    volumes:
      - zookeeper-volume:/pulsar/data/zookeeper

  manager:
    image: apachepulsar/pulsar-manager:v0.3.0
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    ports:
      - '9528:9527'
      - '7750:7750'

volumes:
  zookeeper-volume: {}
  bookie-volume: {}
